name: GraalVM build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17' #      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from Gradle
        id: get_version
        run: echo "VERSION=$(./gradlew properties | grep 'version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Install native build dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y software-properties-common
         sudo add-apt-repository universe
         sudo apt-get update
         sudo apt-get install -y build-essential pkg-config \
            libasound2-dev libavcodec-dev libavformat-dev libavutil-dev \
            libfreetype6-dev libgl-dev libglib2.0-dev libgtk-3-dev \
            libpango1.0-dev libx11-dev libxtst-dev

      - name: Java Check
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Build jar
        run: ./gradlew victusBuild


      - name: Zip installer folder
        run: zip -r VictusHub.zip Installer
            
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "VictusHub ${{ env.VERSION }}"
          body: |
           ### 🧰 Usage


            ```bash
             unzip files
             chmod 777 setup.sh
             ./setup.sh
             ```
              Installation completed!
           
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
          files: VictusHub.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
